services:

  task-manager:
    build:
      context: .
      dockerfile: ./task-manager/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=task-persister
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/task
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
    depends_on:
      - database
      - kafka
    networks:
      - bridge-network

  task-worker:
    build:
      context: .
      dockerfile: ./task-worker/Dockerfile
    ports:
      - '8081:8081'
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=task-processor
    depends_on:
      - kafka
    networks:
      - bridge-network

  database:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: task
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bridge-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'ERROR'
      ZOOKEEPER_LOG4J_LOGGERS: 'kafka=ERROR,kafka.controller=ERROR,kafka.log.LogCleaner=ERROR,state.change.logger=ERROR,kafka.producer.async.DefaultEventHandler=ERROR'
    ports:
      - '2181:2181'
    networks:
      - bridge-network

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: 'tasks-pc:1:1,tasks-ps:1:1'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'ERROR'
      KAFKA_LOG4J_LOGGERS: 'kafka=ERROR,kafka.controller=ERROR,kafka.log.LogCleaner=ERROR,state.change.logger=ERROR,kafka.producer.async.DefaultEventHandler=ERROR'
    networks:
      - bridge-network

volumes:
  postgres-data:


networks:
  bridge-network:
    driver: bridge