spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:task
    username: sa
    password:
    driver-class-name: org.h2.Driver
  kafka:
    bootstrap-servers: localhost:9092
tasks:
  topic-name: tasks
server:
  port: 8080
