spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:h2:mem:task
    username: sa
    password:
    driver-class-name: org.h2.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: task-persister
    admin:
      auto-create: true
tasks:
  topic-name-processing: tasks-pc
  topic-name-persisting: tasks-ps
server:
  port: 8080
