openapi: 3.0.3
info:
  title: Task Manager
  description: Сервис управления задачами
  version: 0.0.1
  contact:
    email: aidarkhalilov4021@mail.ru
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /tasks:
    get:
      operationId: getTasks
      summary: Получение списка задач
      description: Получение списка задач с возможностью фильтрации по статусу.
      parameters:
        - name: status
          in: query
          description: Статус задачи для фильтрации
          required: false
          schema:
            type: string
            enum:
              - NEW
              - PROCESSING
              - COMPLETED
              - FAILED
      responses:
        '200':
          description: Отфильтрованный список задач
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      operationId: createTask
      summary: Создание задачи
      description: Создание новой задачи.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRq'
      responses:
        '201':
          description: Задача успешно создана
          headers:
            Location:
              description: URL новой задачи
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Ошибка передаваемых данных

  /tasks/{taskId}:
    get:
      operationId: getTask
      summary: Получение информации о задаче
      description: Получить информацию о задаче по ее идентификатору.
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Информация о задаче
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задача с данным идентификатором не найдена

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор задачи
          example: 1
        title:
          type: string
          description: Заголовок задачи
          example: "Сделать отчет"
        description:
          type: string
          description: Описание задачи
          example: "Составить финансовый отчет за квартал"
        status:
          type: string
          description: Статус задачи
          enum:
            - NEW
            - PROCESSING
            - COMPLETED
            - FAILED
          example: "NEW"
        createdAt:
          type: string
          format: date-time
          example: '2024-10-20T12:00:00Z'
        completedAt:
          type: string
          format: date-time
          example: '2024-10-20T12:00:10Z'
    TaskRq:
      type: object
      properties:
        title:
          type: string
          description: Заголовок задачи
          example: "Сделать отчет"
        description:
          type: string
          description: Описание задачи
          example: "Составить финансовый отчет за квартал"
      required:
        - title