spring:
  application:
    name: task-worker
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: task-processor
    admin:
      auto-create: true
tasks:
  topic-name-processing: tasks-pc
  topic-name-persisting: tasks-ps
  completionProbability: 0.7
  lower-bound: 5000
  upper-bound: 10000
server:
  port: 8081