spring:
  application:
    name: task-worker
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:task-processor}
tasks:
  topic-name-processing: tasks-pc
  topic-name-persisting: tasks-ps
  completionProbability: 0.7
  lower-bound: 5000
  upper-bound: 10000
logging:
  level:
    org.apache.kafka: ERROR
    kafka: ERROR